# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.define "hlachkarS" do |master|
    master.vm.network "private_network", ip: "192.168.56.110", netmask: "255.255.255.0"
    master.vm.box_check_update = false
    master.vm.hostname = "hlachkarS"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    master.vm.provision "file", source: "config/deployment_app1.yaml", destination: "/home/vagrant/deployment_app1.yaml"
    master.vm.provision "shell", inline: <<-'SHELL'
      # Install K3s and save node token
      curl -sfL https://get.k3s.io | sh -
      sudo kubectl apply -f /home/vagrant/deployment_app1.yaml
    SHELL
  end

end
