# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.synced_folder ".", "/vagrant"

# Prevent Vagrant from replacing the default key
  config.ssh.insert_key = false

  config.vm.define "hlachkarS" do |master|
    master.vm.network "private_network", ip: "192.168.56.110", netmask: "255.255.255.0"
    master.vm.box_check_update = false
    master.vm.hostname = "hlachkarS"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    master.vm.provision "shell", inline: <<-'SHELL'
      # Install K3s and save node token
      curl -sfL https://get.k3s.io | sh - && sudo cat /var/lib/rancher/k3s/server/node-token > /vagrant/master-token
    SHELL
  end

  config.vm.define "hlachkarSW" do |slave|
    slave.vm.network "private_network", ip: "192.168.56.111", netmask: "255.255.255.0"
    slave.vm.box_check_update = false
    slave.vm.hostname = "hlachkarSW"
    slave.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
    end
    slave.vm.provision "shell", inline: <<-SHELL
      MASTER_IP="192.168.56.110"
      TOKEN=$(cat /vagrant/master-token)
      curl -sfL https://get.k3s.io | \
        K3S_URL="https://$MASTER_IP:6443" \
        K3S_TOKEN="$TOKEN" \
        sh -
    SHELL
  end

end
